version: '3'

services:
  go-service:
    build: ./go-service
    volumes:
      - ./go-service:/app
    ports:
      - 8013:8013
    environment: 
      - DB_CONFIG=u1107404_efishery:efishery123!@tcp(5.181.216.74:3306)/u1107404_efishery
      - STEIN_URL=https://stein.efishery.com/v1/storages/5e1edf521073e315924ceab4/list
      - CONVERTER_URL=https://free.currconv.com/api/v7/convert?q=USD_IDR&compact=ultra&apiKey=971e1c9087790b741a01

  py-service:
    build: ./py-service
    volumes:
      - ./py-service:/usr/src/app
    ports:
      - 8015:8015
    environment:
      - HOST=indikost.com
      - DATABASE=u1107404_efishery
      - USER=u1107404_efishery
      - PASSWORD=efishery123!
      - STEIN_URL=https://stein.efishery.com/v1/storages/5e1edf521073e315924ceab4/list
      - CONVERTER_URL=https://free.currconv.com/api/v7/convert?q=IDR_USD&compact=ultra&apiKey=971e1c9087790b741a01
      - SIGNING_KEY=efishery123